run_tests:
    image: openjdk:21-jdk
    before_script: 
        - microdnf install wget -y
        - wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
        - mkdir /usr/local/maven
        - tar xzf apache-maven-3.9.6-bin.tar.gz -C /usr/local/maven/ --strip-components=1
        - echo export 'PATH=$PATH:/usr/local/maven/bin/' > /etc/profile.d/maven.sh
        - chmod +x /etc/profile.d/maven.sh
        - source /etc/profile.d/maven.sh
        - mvn --version
    script:
        - mvn clean verify
