variables:
    IMAGE_NAME: dsoto/token-svc
    IMAGE_TAG: quarkus-app-1.0   

run_tests:
    image: openjdk:21-jdk
    before_script: 
        - microdnf install wget -y
        - wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
        - mkdir /usr/local/maven
        - tar xzf apache-maven-3.9.6-bin.tar.gz -C /usr/local/maven/ --strip-components=1
        - echo export 'PATH=$PATH:/usr/local/maven/bin/' > /etc/profile.d/maven.sh
        - chmod +x /etc/profile.d/maven.sh
        - source /etc/profile.d/maven.sh
        - mvn --version
    script:
        - mvn test

build_image:      
    image: docker:26.1.1
    services:
        - docker:26.1.1-dind
    variables:
        DOCKER_TLS_CERT_DIR: "certs/"
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    script:
        - docker build -f src/main/docker/Dockerfile.jvm -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG
        