quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.http.auth.session.encryption-key=test-only-change-me-32-chars!!
token.issuer=https://apis.internal.dsoto.cl
token.audience=identity-svc
token.access-audiences=identity-svc,onboarding-svc,profile-service
token.service-client.audiences=token-svc,profile-service
token.service-client.allowed-clients=onboarding-svc,profile-svc
token.service-client.secrets.onboarding-svc=test-onboarding-secret
token.service-client.scopes.onboarding-svc=token.identity-events.read,profile.profile-events.read
token.service-client.secrets.profile-svc=test-profile-secret
token.service-client.scopes.profile-svc=profile.profile-events.read
token.service-client.audiences.profile-svc=profile-service
devmode.usageStatistics.enabled=false
quarkus.mailer.mock=true
